[language-server.typescript]
command = "tsc"
args = ["--lsp", "--stdio"]

# Beta tsgo beta binary typescript lsp, now by default since Typescript 7.0
# [language-server.typescript-go]
# command = "tsgo"
# args = ["--lsp", "--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript"]

[[language]]
name = "tsx"
language-servers = ["typescript"]

[[language]]
name = "javascript"
language-servers = ["typescript"]

[[language]]
name = "jsx"
language-servers = ["typescript"]
